### ISSUE TITLE
are they any Commands API?

### ISSUE THREAD

**Issue by Outfit8TSB** [YvanMazy/TransferProxy#5]
i want to make a TransferProxy Plugin Related To ViaProxy Public Wildcard Hostname to Reincarnate ViaProxyConnect.

but i cant unless if there is command api.
here is my plugin information i require.

`/ViaProxy address port version hostname` -> `address_port_version.viaproxy.hostname`

```
information:
defaultaddress: test.geysermc.org
defaultport: 25565
defaultversion: 1.21.1
defaulthostname: anarchyconnect.duckdns.org
```

it used to connect multiple instance.

**Comment by YvanMazy** [comment]
Hello,

The concept of TransferProxy being to **not** hold the player's connection after the transfer, it is not possible to have a command system.
To make a command like this, you must do it on a Spigot plugin (or any other server holding the player's connection)

**Comment by Outfit8TSB** [comment]
Aw man...

**Comment by YvanMazy** [comment]
Did you understand the limitation? The issue can be closed?

**Comment by Outfit8TSB** [comment]
I understand the limitation, guess that this is not for ViaProxy Public Wildcard Domain Handling.
